# Generated by Django 5.0.3 on 2024-04-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
