# Generated by Django 5.0.3 on 2024-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0002_ponto_turisticos_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
