# Generated by Django 5.0.3 on 2024-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0003_ponto_turisticos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacoes.avaliacoes'),
        ),
    ]
