# Generated by Django 5.0.3 on 2024-04-08 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ponto_turisticos_avaliacao'),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
